---
- name: "Creating TLS certificate directory"
  ansible.builtin.file:
    path: /etc/ssl/{{ fqdn }}
    state: directory
    modification_time: preserve
    access_time: preserve
    owner: root
    group: root
    mode: '0755'

- name: "Copying TLS certificate to the proxy"
  ansible.builtin.copy:
    src: "{{ item }}" # ensure the file exists
    dest: /etc/ssl/{{ fqdn }}/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - customssl.crt
    - customssl.key
