---
# Include connection specific tasks
- name: "DHIS2 instance setup with  {{ ansible_connection }}"
  ansible.builtin.include_tasks: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['instances']

- name: "Include tasks to setup postgresql"
  ansible.builtin.include_tasks: generate_db_pass.yml
  when: inventory_hostname in groups['instances']

- name: "Include postgresql tasks"
  ansible.builtin.include_tasks: postgresql_db.yml
  when: inventory_hostname in groups['databases']

- name: "Include tasks for DHIS2 setup "
  ansible.builtin.include_tasks: dhis2_setup.yml
  when: inventory_hostname in groups['instances']
